force-app/main/default/objects/Log_Entry__c/Log_Entry__c.object-meta.xml
<CustomObject>
    <label>Log Entry</label>
    <nameField>
        <label>Log Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Log Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log_Entry__c/fields/Keep_Long_Term__c.field-meta.xml
<CustomField>
    <fullName>Keep_Long_Term__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Keep Long Term</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ErrorLogCleanupBatch.cls
public with sharing class ErrorLogCleanupBatch implements Database.Batchable<Log_Entry__c> {
    public Iterable<Log_Entry__c> start(Database.BatchableContext bc) {
        return [
            SELECT Id 
            FROM Log_Entry__c 
            WHERE CreatedDate <= LAST_N_DAYS:15 
            AND Keep_Long_Term__c = false
        ];
    }

    public void execute(Database.BatchableContext bc, List<Log_Entry__c> scope) {
        delete scope;
    }

    public void finish(Database.BatchableContext bc) {
        System.debug('Error log cleanup batch completed');
    }
}